### ISSUE TITLE
cant build the page with mkdocs

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/dimeanalytics#4]
These instructions does not work for me:

> To contribute, check out the `gh-pages` branch. Update only the .md materials in the `/_MkDocs/` folder. Then, to compile the site, run:

```
cd _MkDocs
mkdocs build
```
> Finally, delete eveything in the root directory except `/_MkDocs/`; copy the contents of `/_MkDocs/site/` into the root directory; and submit a pull request to the `gh-pages` branch.

Do you need to install something called `mkdocs` first? The `mkdocs build` command should be run in a terminal/command line etc. right? We should probably explicitly mention that.

I get this error below in git bash:

![image](https://user-images.githubusercontent.com/15911801/53429721-2beb0180-39bb-11e9-8adb-536c2faef20f.png)

Also, the copy of material from site to root could be typed up in the code example after `mkdocs build` to make sure that we all do the same thing.

**Comment by bbdaniels** [comment]
Yes - need to install from https://www.mkdocs.org/
I didn't copy by shell command 😬 but I should figure out how to do it correctly

**Comment by kbjarkefur** [comment]
Fixed as of b323b0df. The new set up is well documented in the main README.md file
